In [1]:
import pandas as pd
import requests
import os

In [2]:
#url for all calls
base_url = "https://fantasy.premierleague.com/api/"
#folder where data will be saved       
folder = r"C:\Users\JesseOnu\FPL new\playerid" 
output = f"{folder}.csv"

In [3]:
#call api
response = requests.get(base_url + "bootstrap-static/")

In [4]:
#convert to json
data = response.json()

In [5]:
print(type(data))
print(type(response))
print(response.status_code)

<class 'dict'>
<class 'requests.models.Response'>
200

In [6]:
#displaying availabl fields
print(data["elements"][0].keys())

dict_keys(['can_transact', 'can_select', 'chance_of_playing_next_round', 'chance_of_playing_this_round', 'code', 'cost_change_event', 'cost_change_event_fall', 'cost_change_start', 'cost_change_start_fall', 'dreamteam_count', 'element_type', 'ep_next', 'ep_this', 'event_points', 'first_name', 'form', 'id', 'in_dreamteam', 'news', 'news_added', 'now_cost', 'photo', 'points_per_game', 'removed', 'second_name', 'selected_by_percent', 'special', 'squad_number', 'status', 'team', 'team_code', 'total_points', 'transfers_in', 'transfers_in_event', 'transfers_out', 'transfers_out_event', 'value_form', 'value_season', 'web_name', 'known_name', 'region', 'team_join_date', 'birth_date', 'has_temporary_code', 'opta_code', 'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries', 'tackles', 'defensive_contribution', 'starts', 'expected_goals', 'expected_assists', 'expected_goal_involvements', 'expected_goals_conceded', 'corners_and_indirect_freekicks_order', 'corners_and_indirect_freekicks_text', 'direct_freekicks_order', 'direct_freekicks_text', 'penalties_order', 'penalties_text', 'scout_risks', 'influence_rank', 'influence_rank_type', 'creativity_rank', 'creativity_rank_type', 'threat_rank', 'threat_rank_type', 'ict_index_rank', 'ict_index_rank_type', 'expected_goals_per_90', 'saves_per_90', 'expected_assists_per_90', 'expected_goal_involvements_per_90', 'expected_goals_conceded_per_90', 'goals_conceded_per_90', 'now_cost_rank', 'now_cost_rank_type', 'form_rank', 'form_rank_type', 'points_per_game_rank', 'points_per_game_rank_type', 'selected_rank', 'selected_rank_type', 'starts_per_90', 'clean_sheets_per_90', 'defensive_contribution_per_90'])

In [7]:
#keeping necesarry fields
df = pd.DataFrame(data["elements"])

df = df[["id", "code", "first_name", "second_name", "web_name", "photo", "element_type"]]

In [8]:
df.head()

,id,code,first_name,second_name,web_name,photo,element_type
0,1,154561,David,Raya Martín,Raya,154561.jpg,1
1,2,109745,Kepa,Arrizabalaga Revuelta,Arrizabalaga,109745.jpg,1
2,3,463748,Karl,Hein,Hein,463748.jpg,1
3,4,551221,Tommy,Setford,Setford,551221.jpg,1
4,5,226597,Gabriel,dos Santos Magalhães,Gabriel,226597.jpg,2

In [9]:
#replace 'jpg' with 'png' as images dont work with jpg
df['photo'] = df['photo'].str.replace('jpg', 'png', regex = False)

In [10]:
#add prefix to photo
df['photo'] = "https://resources.premierleague.com/premierleague25/photos/players/110x140/" + df['photo']
df.head(1)

,id,code,first_name,second_name,web_name,photo,element_type
0,1,154561,David,Raya Martín,Raya,https://resources.premierleague.com/premierlea...,1

In [11]:
df.iloc[0]['photo']

'https://resources.premierleague.com/premierleague25/photos/players/110x140/154561.png'

In [12]:
#making sure theres no blank webnames
(df['web_name']=='').sum()

np.int64(0)

In [13]:
#check for no duplicates
df['id'].duplicated().sum()

np.int64(0)

In [14]:
df.to_csv(output, index = False)